version: "3.7"

services:
  user_db:
    container_name: user_posgtres_db
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - user_pgdata:/var/lib/postgresql/data

  user_app:
    container_name: user_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 9000:8000
    depends_on:
      - user_db
    expose:
      - 9000
    restart: always
volumes:
  user_pgdata:

networks:
  default:
    external: false
    name: user_crud_network
